Misc changes to make deb-build happier

diff --git a/microdep/perfsonar-microdep/unibuild-packaging/deb/perfsonar-microdep-map.prerm b/microdep/perfsonar-microdep/unibuild-packaging/deb/perfsonar-microdep-map.prerm
--- a/microdep/perfsonar-microdep/unibuild-packaging/deb/perfsonar-microdep-map.prerm
+++ b/microdep/perfsonar-microdep/unibuild-packaging/deb/perfsonar-microdep-map.prerm
@@ -1,15 +1,59 @@
-# Clean up open access to Microdep opensearch index
-TMPROLESYML=$(mktemp)
-grep -v -x -F -f /etc/perfsonar/microdep/roles_yml_patch /usr/lib/perfsonar/archive/config/roles.yml > $TMPPIPELINE && mv $TMPROLESYML /usr/lib/perfsonar/archive/config/roles.yml
+#!/bin/sh
+# prerm script for perfsonar-microdep-map
+#
+# see: dh_installdeb(1)
 
-# Refresh config of opensearch security
-/usr/lib/perfsonar/archive/perfsonar-scripts/pselastic_secure_pre.sh
-/usr/lib/perfsonar/archive/perfsonar-scripts/pselastic_secure_pos.sh
+set -e
 
-# Remove Microdep button from Grafana main dashboard (if present)
-grep -q  "Microdep map" /usr/lib/perfsonar/grafana/dashboards/toolkit/perfsonar-main.json
-if [ $? -eq 0 ]; then
-    DASHBOARDFILE=$(mktemp)
-    jq  'del( .panels[] | select(.options.content != null ) | select (.options.content | contains("Microdep map")))' /usr/lib/perfsonar/grafana/dashboards/toolkit/perfsonar-main.json > $DASHBOARDFILE
-    mv $DASHBOARDFILE /usr/lib/perfsonar/grafana/dashboards/toolkit/perfsonar-main.json
-fi
+# summary of how this script can be called:
+#        * <prerm> `remove'
+#        * <old-prerm> `upgrade' <new-version>
+#        * <new-prerm> `failed-upgrade' <old-version>
+#        * <conflictor's-prerm> `remove' `in-favour' <package> <new-version>
+#        * <deconfigured's-prerm> `deconfigure' `in-favour'
+#          <package-being-installed> <version> `removing'
+#          <conflicting-package> <version>
+# for details, see https://www.debian.org/doc/debian-policy/ or
+# the debian-policy package
+
+case "$1" in
+    remove | deconfigure)
+	# Clean up open access to Microdep opensearch index
+	if [ -e /usr/lib/perfsonar/archive/config/roles.yml ]; then
+	    TMPROLESYML=$(mktemp)
+	    grep -v -x -F -f /etc/perfsonar/microdep/roles_yml_patch /usr/lib/perfsonar/archive/config/roles.yml > $TMPPIPELINE && mv $TMPROLESYML /usr/lib/perfsonar/archive/config/roles.yml
+
+	    # Refresh config of opensearch security
+	    /usr/lib/perfsonar/archive/perfsonar-scripts/pselastic_secure_pre.sh
+	    /usr/lib/perfsonar/archive/perfsonar-scripts/pselastic_secure_pos.sh
+	fi
+	
+	# Remove Microdep button from Grafana main dashboard (if present)
+	if [ -e /usr/lib/perfsonar/grafana/dashboards/toolkit/perfsonar-main.json ]; then
+	    grep -q  "Microdep map" /usr/lib/perfsonar/grafana/dashboards/toolkit/perfsonar-main.json
+	    if [ $? -eq 0 ]; then
+		DASHBOARDFILE=$(mktemp)
+		jq  'del( .panels[] | select(.options.content != null ) | select (.options.content | contains("Microdep map")))' /usr/lib/perfsonar/grafana/dashboards/toolkit/perfsonar-main.json > $DASHBOARDFILE
+		mv $DASHBOARDFILE /usr/lib/perfsonar/grafana/dashboards/toolkit/perfsonar-main.json
+	    fi
+	fi
+	;;
+
+    upgrade|failed-upgrade)
+	;;
+    
+    *)
+        echo "prerm called with unknown argument \`$1'" >&2
+        exit 1
+	;;
+esac
+
+# dh_installdeb will replace this with shell code automatically
+# generated by other debhelper scripts.
+
+#DEBHELPER#
+
+exit 0
+
+
+
