5.3.0 (#64)
* Fixed missing ip-to-name resolution when an ip is gives as name

* Ensured geopos-lookup when ip is source

* Removed duplicate requests towards opensearch + fixed some 'sum-event v.s. event' issues

* Misc changes to enable ipv6. All opensearch requests now via cgi call.

* Fixed error in ip version test

* Introduced config file for gap analysis.

* Another round of debugging config file for gap analysis

* Added support for config file for trace-ana.

* Final fix to enable and apply config file for trace-ana.

* Changed order of removal to avoid error messages on package removal.

* Forgot to add trace ana config file.

* Ensured ip-version is passed to tracetree + also to/from ip addresses

* Ensured ip-version is passed to tracetree + also to/from ip addresses

* First test of preparation for http archiving from ana-scripts

* Ensured full removal and reinstall on upgrades etc.

* Return code fix and apache conf enabeling

* Pipeline rearranged and updated to better handle several variants of analytic inputs.

* Added ana_tool field in json output from analysis, and related tagging in logstash pipeline

* Enabled putting of gap-ana results via http in systemd service

* Disabled some dead code.

* Empty placeholder for postrm actions for deb.

* Added updated logstash pipeline

* HTTP to logstash for trace-analysis (+ some formatting, spelling and other fixes)

* Replace match-statement with elif for python <3.10 compatibility

* Fixed query_index to be set properly and applied by elastic-get-date-type.pl

diff --git a/microdep/perfsonar-microdep/unibuild-packaging/deb/perfsonar-microdep-map.prerm b/microdep/perfsonar-microdep/unibuild-packaging/deb/perfsonar-microdep-map.prerm
--- a/microdep/perfsonar-microdep/unibuild-packaging/deb/perfsonar-microdep-map.prerm
+++ b/microdep/perfsonar-microdep/unibuild-packaging/deb/perfsonar-microdep-map.prerm
@@ -17,7 +17,8 @@ set -e
 # the debian-policy package
 
 case "$1" in
-    remove | deconfigure)
+#    remove | deconfigure)
+    remove | deconfigure | upgrade | failed-upgrade)
 	
 	# Remove Microdep button from Grafana main dashboard (if present)
 	if [ -e /usr/lib/perfsonar/grafana/dashboards/toolkit/perfsonar-main.json ]; then
@@ -27,10 +28,20 @@ case "$1" in
 		mv $DASHBOARDFILE /usr/lib/perfsonar/grafana/dashboards/toolkit/perfsonar-main.json
 	    fi
 	fi
+	
+	# Disable apache config
+        if [ -e /usr/share/apache2/apache2-maintscript-helper ]; then
+            . /usr/share/apache2/apache2-maintscript-helper
+	    
+            apache2_invoke disconf apache-microdep-map
+        else
+	    a2disconf apache-microdep-map
+	    systemctl reload apache2.service || true
+	fi
 	;;
 
-    upgrade|failed-upgrade)
-	;;
+#    upgrade|failed-upgrade)
+#	;;
     
     *)
         echo "prerm called with unknown argument \`$1'" >&2
